{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scope.componentName" (dict "component" "api" "context" .) }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "scope.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "scope.selectorLabels" (dict "component" "api" "context" .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
{{- end -}}
